# Generated by Django 4.0.1 on 2022-01-19 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_email', models.EmailField(default='webmail@sgonzalezdev.com', max_length=254)),
                ('user_reason', models.TextField()),
                ('user_phone', models.CharField(max_length=20)),
                ('user_message', models.TextField()),
                ('user_contact_via', models.CharField(max_length=10)),
            ],
        ),
    ]
